docs/UserGuide.md

Top portion and add feature added into User Guide.

Add add feature in UserGuide.md

---

docs/DeveloperGuide.md

UC05 is "Mark as incomplete"
UC06 is "Warn on invalid command"

Add in UC05 and UC06 into DG

---

docs/team/jcsnap.md

Add PPP Section for Justin.  
**Note:**
This PPP is in progress, and will be filled in the future.

Add PPP section for jcsnap

---

docs/team/maypfv.md

Add PPP file for May.
Still in progress and more information will be added in.

Update maypfv.md PPP file

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/task/Status.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/storage/JsonAdaptedTask.java
src/main/java/seedu/address/ui/TaskCard.java
src/main/resources/view/TaskListCard.fxml
src/test/java/seedu/address/model/task/StatusTest.java
src/test/java/seedu/address/model/task/TaskTest.java
src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java

Integrate status into task model

Task status integration

---

docs/team/jcsnap.md

Update PPP for JCSnap

---

docs/DeveloperGuide.md

Added the Future Improvements section to the Sort Command.

Add Future Improvements to Sort

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/NoteCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/model/task/Task.java
src/test/java/seedu/address/logic/commands/MarkCommandTest.java
src/test/java/seedu/address/logic/commands/NoteCommandTest.java
src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
src/test/java/seedu/address/testutil/TaskBuilder.java

Removed all unecessary constructors. The only constructors that are left now are:
1. The one that only takes in the description.
2. The one that takes in everything
Fixed all the instantiations to account for all fields.

Fix constructor and instantiation to include all fields

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/task/Deadline.java
src/main/java/seedu/address/model/task/Task.java
src/test/data/JsonSerializableTaskWiseTest/duplicateTaskTaskWise.json
src/test/data/JsonSerializableTaskWiseTest/invalidTaskTaskWise.json
src/test/data/JsonSerializableTaskWiseTest/typicalTasksTaskWise.json
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/sort/SortUtilTest.java
src/test/java/seedu/address/model/task/DeadlineTest.java
src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java

This PR updates the Deadline class and the associated JSON configurations required to support the changes.
Updates to the Unit Tests were also made to ensure they function as usual prior to the update to Deadline.

Update Deadline and Unit Tests

---

src/main/java/seedu/address/logic/sort/SortUtil.java
src/main/java/seedu/address/model/task/Priority.java
src/test/java/seedu/address/logic/sort/SortUtilTest.java

This PR represents the final revision to the Sort feature, which now allows users to sort their tasks by Priority.

Implement Sort by Priority

---

src/main/java/seedu/address/model/task/Deadline.java
src/main/java/seedu/address/ui/TaskCard.java

Just a small change to the TaskCard class when displaying the Deadline; Deadline can no longer be null, so that has been removed in this PR

Change code for displaying Task card

---

src/main/java/seedu/address/ui/MainWindow.java

Clear right panel after every command

---

src/main/java/seedu/address/ui/TaskCard.java
src/main/java/seedu/address/ui/TaskListPanel.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/TaskListCard.fxml
src/main/resources/view/TaskListPanel.fxml

Implemented some updates to the UI
* Fixed an issue where Member labels are causing the inner layout of the TaskCard to expand
* Set minimum window size to `minWidth="675" minHeight="650"`
* Set minimum row height of the TaskCard to `prefHeight="115"`

Update UI Elements

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/TaskWiseParser.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/task/Note.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/UiManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java

Type
```
view [INDEX]
```
To display information about the task on the right panel.
close #112

Add View Command

---

src/main/java/seedu/address/ui/TaskCard.java
src/main/resources/view/TaskListCard.fxml

Implemented a fix to the unresponsive UI that does not scale the content of the GridPane.

Fix Unresponsive UI

---

src/main/java/seedu/address/ui/MainWindow.java

kinda hacky but its the only way

Fix bug where view does not work

---

src/main/java/seedu/address/ui/TaskCard.java

Currently, the member labels will overflow when more than 5 labels are added.
This PR solves that issue.

Fix Overflowing Member List

---

docs/UserGuide.md

Fix hyperlink bug under tutorial

---

docs/DeveloperGuide.md
docs/team/jcsnap.md

1. Fix text for note developer guide alternatives considered.
2. Fix activity diagrams links for note and view.
3. PPP

Update DG mistakes and PPP

---

docs/UserGuide.md
docs/team/asdfghjkxd.md
docs/team/jcsnap.md
docs/team/maypfv.md
docs/team/seantehds.md
docs/team/sebtey.md

This PR fixes some documentation bugs that we may have.

Fix Documenation Bugs

---

docs/DeveloperGuide.md
docs/UserGuide.md

Minor fix to headers and typo.

Fix table of content in user guide and developer guide

---

docs/team/asdfghjkxd.md
docs/team/jcsnap.md
docs/team/maypfv.md
docs/team/seantehds.md
docs/team/sebtey.md
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/logic/sort/SortUtil.java
src/main/java/seedu/address/logic/sort/enums/SortOrderEnum.java
src/main/java/seedu/address/logic/sort/enums/SortTypeEnum.java
src/main/java/seedu/address/ui/TaskCard.java
src/main/java/seedu/address/ui/TaskListPanel.java
src/test/java/seedu/address/commons/core/LogsCenterTest.java
src/test/java/seedu/address/logic/sort/SortUtilTest.java
src/test/java/seedu/address/logic/sort/enums/SortOrderEnumTest.java
src/test/java/seedu/address/logic/sort/enums/SortTypeEnumTest.java

This PR aims to improve the overall code quality of some pieces of code, by refactoring methods into smaller methods, and changing variable names to something more indicative of what the variable contains.

Improve code quality

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/TaskWiseParser.java
src/main/java/seedu/address/storage/JsonAdaptedMember.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/TaskWiseParserTest.java

* Fix code quality of the following classes with long methods (LOC > 30)
1. EditCommandParser
2.  TaskWiseParser
* Added and edited test cases for EditCommandParserTest
* Fix error message of edit command for "invalid index"

Fixed up code quality and bug

---

docs/team/asdfghjkxd.md
docs/team/jcsnap.md
docs/team/maypfv.md
docs/team/seantehds.md
docs/team/sebtey.md

Updated PPP summary for all of us. Also, did some updates to Seb's PPP

PPP updates
